version: '3'
services:
  myapp-main:
    image: venuesnap
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=
      - spring.datasource.password=
      - spring.datasource.username=
      - spring.datasource.driver-class-name=